### ISSUE TITLE
Stack is really out of date in the minimal installer download

### ISSUE THREAD

**Issue by nackjicholson** [ghcformacosx/ghc-dot-app#47]
I installed ghc, stack, and cabal via the minimal installers OSX link on this page https://www.haskell.org/downloads and now I'm running into some strange resolver problems while trying to get started with stack. I run stack ghci it tells me that it wants 7.10.3 and to run stack setup. Setup then says it installed ghc@7.10.2. Here is a paste of my terminal output http://lpaste.net/152629.

I ended up putting this on stackoverflow and IRC, got some help and the fix is described below: 

(via my comment on [stackoverflow](http://stackoverflow.com/questions/35450713/haskell-stack-resolver-error-just-trying-to-run-ghci))

Apparently the version of stack in that package is 0.1.2.0 which is super old, and this bug is very dated. I don't know why the .org downloads page installs an ancient version of the tool, but my fix ended up being to download stack manually from here: https://github.com/commercialhaskell/stack/blob/master/doc/install_and_upgrade.md unzipped it and I ran 

```
mv ~/Downloads/stack-1.0.2-osx-x86_64/stack /Applications/ghc-7.10.2.app/Contents/bin/stack
```

Which puts the updated stack in place of the old one. Seems to work!

Please consider packaging your download with an up to date version of stack.

**Comment by mgsloan** [comment]
Thanks for writing this report, @nackjicholson !  It's a pain when people use archaic versions because

A) They get a less than ideal initial impression of haskell

B) We get issues reported to our tracker / IRC which are no longer issues with recent stack

Folks using this version of stack has cropped up a fair amount recently - http://ircbrowse.net/browse/haskell?id=21785009&timestamp=1447371258#t1447371258 https://github.com/commercialhaskell/stack/issues/1709

**Comment by mgsloan** [comment]
Another today https://gist.github.com/nuttycom/c21fda8b6f1e26a41733

**Comment by gbaz** [comment]
Cabal is really out of date too. We really need a new release of this, just upgrading those two binaries...
